/** A sample Buy Lead payload, shaped like the webhook body of the source n8n workflow. */
export const SAMPLE_LEAD = {
  display_id: "BL00012345",
  title: "Cotton",
  description: "Need raw cotton bales for our spinning unit, regular supply required.",
  mcat_name: "Raw Cotton",
  company_name_flag: 0,
  gst_flag: 0,
  company_address_flag: 0,
  city: "Indore",
  state: "Madhya Pradesh",
  product_viewed_name: ["Raw Cotton Bales", "Organic Cotton"],
  product_prices: [42000, 48000],
  quantity: 5000,
  quantity_unit: "Ton",
  mcat_q1: 38000,
  mcat_median: 45000,
  mcat_q3: 52000,
  isq_asked: ["Color", "Packaging Type", "Usage/Application"],
  isq_filled: ["White", "Bales", "Spinning"],
};
